---
# tasks file for roles/datadisk-HumberID

- name: Partition the disk
  ansible.builtin.command:
    cmd: "parted {{ disk_device }} mkpart primary {{ item.fstype }} {{ item.start }} {{ item.end }}"
  loop: "{{ partition_sizes }}"

- name: Create filesystems
  ansible.builtin.filesystem:
    fstype: "{{ item.fstype }}"
    dev: "{{ disk_device }}{{ loop.index }}"
  loop: "{{ partition_sizes }}"

- name: Create mount points
  ansible.builtin.file:
    path: "{{ item.mountpoint }}"
    state: directory
  loop: "{{ partition_sizes }}"

- name: Mount partitions
  ansible.builtin.mount:
    path: "{{ item.mountpoint }}"
    src: "{{ disk_device }}{{ loop.index }}"
    fstype: "{{ item.fstype }}"
    opts: defaults
    state: mounted
  loop: "{{ partition_sizes }}"

- name: Persist mounts in /etc/fstab
  ansible.builtin.mount:
    path: "{{ item.mountpoint }}"
    src: "{{ disk_device }}{{ loop.index }}"
    fstype: "{{ item.fstype }}"
    opts: defaults
    state: mounted
  loop: "{{ partition_sizes }}"
